#设置微服务的名称： product-data-service
#设置注册中心的地址： http://localhost:8761/eureka/ , 与 eureka-server 中的配置 application.yml 遥相呼应
spring:
  application:
    name: product-data-service
    #链路追踪服务器
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/