thymeleaf:
  servlet:
    content-type: text/html
  mode: HTML5
  encoding: UTF-8
  cache: false
  prefix: classpath:/tempaltes
  suffix: .html

spring:
  application:
    name: product-view-service-feign
    #zipkin 链路追踪服务器
    zipkin:
      base-url: http://localhost:9411


