thymeleaf:
  servlet:
    content-type: text/html
  mode: HTML5
  encoding: UTF-8
  cache: false
  prefix: classpath:/tempaltes
  suffix: .html

spring:
  application:
    name: product-view-service-feign
    #zipkin 链路追踪服务器
    zipkin:
      base-url: http://localhost:9411

#路径访问允许，这样才能访问 /actuator/bus-refresh  这是消息总线
management:
  endpoints:
    web:
      exposure:
        include: "*"  #打开全部请求端点
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
#断路器开启：
feign:
  hystrix:
    enabled: true

